import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || Deno.env.get("SUPABASE_SERVICE_KEY")!;
const headers = { apikey: SERVICE_KEY, Authorization: `Bearer ${SERVICE_KEY}`, "Content-Type": "application/json" };
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type", "Access-Control-Allow-Methods": "POST, OPTIONS", "Content-Type": "application/json" } });
const db = (table: string, query = "", init: RequestInit = {}) => fetch(`${SUPABASE_URL}/rest/v1/${table}${query}`, { ...init, headers: { ...headers, ...(init.headers || {}) } });
const one = async (table: string, query: string) => { const r = await db(table, query); const x = await r.json(); return Array.isArray(x) ? x[0] : null; };
const normWA = (v: string) => { let s = String(v || "").replace(/\D/g, ""); if (s.startsWith("0")) s = "62" + s.slice(1); if (!s.startsWith("62") && s) s = "62" + s; return s; };
const today = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Jakarta" }).format(new Date());
async function session(token: string | null) { if (!token) return null; return one("app_sessions", `?token=eq.${encodeURIComponent(token)}&expires_at=gt.${encodeURIComponent(new Date().toISOString())}&select=*`); }
function segment(c: any) { const days = c.tanggal_terakhir_beli ? Math.floor((Date.now() - new Date(String(c.tanggal_terakhir_beli).slice(0,10) + "T00:00:00").getTime()) / 86400000) : null; if (!c.tanggal_terakhir_beli || Number(c.jumlah_transaksi || 0) === 0) return "Baru"; if ((days || 0) > 180) return "Dormant"; if ((days || 0) > 60) return "At-Risk"; if (Number(c.total_belanja || 0) >= 2000000 || Number(c.jumlah_transaksi || 0) >= 8) return "VIP"; return "Active Routine"; }
function allowed(role: string, name: string) { const owner = ["campaignList","campaignSave","campaignStatus","couponList","couponSave","report"]; if (owner.includes(name)) return role === "Owner"; return ["Owner","Apoteker","Kasir"].includes(role); }
async function validate(data: any, s: any) {
  const code = String(data.code || "").trim().toUpperCase(); const wa = normWA(data.nomor_wa || "");
  if (!code) throw new Error("Kode kupon wajib diisi."); if (!wa) throw new Error("Pilih pelanggan terlebih dahulu.");
  const c = await one("master_customer", `?cabang_id=eq.${encodeURIComponent(s.cabang_id || "KARLA")}&nomor_wa=eq.${encodeURIComponent(wa)}&select=*`); if (!c) throw new Error("Pelanggan belum terdaftar.");
  const cp = await one("promo_coupons", `?cabang_id=eq.${encodeURIComponent(s.cabang_id || "KARLA")}&code=eq.${encodeURIComponent(code)}&is_active=eq.true&select=*,promo_campaigns!inner(name,status,starts_at,ends_at),promo_segment_targets(segment,customer_type)`); if (!cp) throw new Error("Kode kupon tidak ditemukan atau tidak aktif.");
  const now = Date.now(), start = new Date(cp.promo_campaigns.starts_at).getTime(), end = new Date(cp.promo_campaigns.ends_at).getTime(); if (cp.promo_campaigns.status !== "ACTIVE" || now < start || now > end) throw new Error("Kampanye kupon tidak aktif atau sudah berakhir.");
  const seg = segment(c); const targets = cp.promo_segment_targets || []; if (!targets.some((t: any) => t.segment === seg && (t.customer_type == null || t.customer_type === data.tipe_customer))) throw new Error("Pelanggan tidak termasuk segmen promo ini.");
  const subtotal = Number(data.subtotal || 0); if (subtotal < Number(cp.min_purchase || 0)) throw new Error(`Minimum belanja kupon adalah Rp${Number(cp.min_purchase || 0).toLocaleString("id-ID")}.`);
  const discount = cp.discount_type === "PERCENT" ? Math.min(subtotal * Number(cp.discount_value || 0) / 100, cp.max_discount == null ? subtotal : Number(cp.max_discount)) : Math.min(Number(cp.discount_value || 0), subtotal);
  const uses = await db("promo_redemptions", `?coupon_id=eq.${cp.id}&customer_id=eq.${c.id}&status=eq.APPLIED&select=id&limit=1000`); const used = uses.ok ? (await uses.json()).length : 0; if (used >= Number(cp.usage_limit_per_customer || 1)) throw new Error("Kupon sudah pernah digunakan oleh pelanggan ini.");
  return { valid: true, code: cp.code, campaign_name: cp.promo_campaigns.name, segment: seg, discount };
}
async function action(name: string, data: any, s: any) {
  if (!allowed(s.role, name)) throw new Error(`Akses ditolak untuk role ${s.role}.`);
  const branch = s.cabang_id || "KARLA";
  if (name === "campaignList") { const r = await db("promo_campaigns", `?cabang_id=eq.${encodeURIComponent(branch)}&select=*,promo_segment_targets(segment,customer_type),promo_coupons(id,code,discount_type,discount_value,max_discount,min_purchase,usage_limit_total,usage_limit_per_customer,is_active)&order=created_at.desc&limit=200`); if (!r.ok) throw new Error(await r.text()); return await r.json(); }
  if (name === "campaignSave") { const p = { cabang_id: branch, name: String(data.name || "").trim(), description: data.description || "", starts_at: data.starts_at, ends_at: data.ends_at, status: data.status || "DRAFT", created_by: s.username, updated_at: new Date().toISOString() }; if (!p.name || !p.starts_at || !p.ends_at) throw new Error("Nama dan periode kampanye wajib diisi."); const r = await db("promo_campaigns", "", { method: "POST", headers: { ...headers, Prefer: "return=representation" }, body: JSON.stringify(p) }); if (!r.ok) throw new Error(await r.text()); const row = (await r.json())[0]; const targets = (data.segments || []).map((x: string) => ({ campaign_id: row.id, segment: x, customer_type: data.customer_type || null })); if (targets.length) { const tr = await db("promo_segment_targets", "", { method: "POST", headers: { ...headers, Prefer: "return=minimal" }, body: JSON.stringify(targets) }); if (!tr.ok) throw new Error(await tr.text()); } return row; }
  if (name === "campaignStatus") { const status = String(data.status || ""); if (!["ACTIVE","PAUSED","ARCHIVED"].includes(status)) throw new Error("Status kampanye tidak valid."); const r = await db("promo_campaigns", `?id=eq.${encodeURIComponent(data.id)}&cabang_id=eq.${encodeURIComponent(branch)}`, { method: "PATCH", headers: { ...headers, Prefer: "return=minimal" }, body: JSON.stringify({ status, updated_at: new Date().toISOString() }) }); if (!r.ok) throw new Error(await r.text()); return true; }
  if (name === "couponList") { const r = await db("promo_coupons", `?cabang_id=eq.${encodeURIComponent(branch)}&select=*,promo_campaigns(name,status,starts_at,ends_at)&order=created_at.desc&limit=200`); if (!r.ok) throw new Error(await r.text()); return await r.json(); }
  if (name === "couponSave") { const p: any = { campaign_id: data.campaign_id, cabang_id: branch, code: String(data.code || "").trim().toUpperCase(), discount_type: data.discount_type || "FIXED", discount_value: Number(data.discount_value || 0), max_discount: data.max_discount === "" || data.max_discount == null ? null : Number(data.max_discount), min_purchase: Number(data.min_purchase || 0), usage_limit_total: data.usage_limit_total === "" || data.usage_limit_total == null ? null : Number(data.usage_limit_total), usage_limit_per_customer: Math.max(1, Number(data.usage_limit_per_customer || 1)), is_active: data.is_active !== false }; if (!p.campaign_id || !p.code || p.discount_value <= 0) throw new Error("Kampanye, kode, dan nilai promo wajib diisi."); const r = await db("promo_coupons", "", { method: "POST", headers: { ...headers, Prefer: "return=minimal" }, body: JSON.stringify(p) }); if (!r.ok) throw new Error(await r.text()); return true; }
  if (name === "validate") return validate(data, s);
  if (name === "report") { const r = await db("promo_redemptions", `?cabang_id=eq.${encodeURIComponent(branch)}&select=campaign_id,coupon_id,customer_id,invoice_no,discount_amount,redeemed_at,status,promo_campaigns(name),promo_coupons(code)&order=redeemed_at.desc&limit=1000`); if (!r.ok) throw new Error(await r.text()); const rows = await r.json(); return { redemptions: rows.length, unique_customers: new Set(rows.map((x: any) => x.customer_id)).size, discount_total: rows.reduce((n: number, x: any) => n + Number(x.discount_amount || 0), 0), rows }; }
  if (name === "checkout") { const payload = { p_username: s.username, p_nomor_wa: data.nomor_wa || "", p_nama_pelanggan: data.nama_pelanggan || "Umum", p_tipe_customer: data.tipe_customer || "Umum", p_items: data.items || [], p_cabang_id: branch, p_diskon: data.diskon || 0, p_bayar: data.bayar || 0, p_reward_id: data.reward_id || null, p_coupon_code: String(data.coupon_code || "").trim().toUpperCase() }; const r = await db("rpc/pos_checkout_promo", "", { method: "POST", headers, body: JSON.stringify(payload) }); if (!r.ok) throw new Error(await r.text() || "Checkout promo gagal."); return await r.json(); }
  throw new Error("Aksi promo tidak dikenal.");
}
Deno.serve(async (req: Request) => { if (req.method === "OPTIONS") return json({ ok: true }); try { const body = await req.json(); const [name, data, token] = body.args || []; const s = await session(token); if (!s) return json({ ok: false, error: "Sesi berakhir. Silakan login kembali.", code: "NO_SESSION" }); return json({ ok: true, data: await action(name, data || {}, s) }); } catch (e) { return json({ ok: false, error: e instanceof Error ? e.message : String(e) }, 500); } });
